const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),vm=require('node:vm'),{spawn}=require('node:child_process'),{buildSync}=require('esbuild'),{unzipSync,strFromU8}=require('fflate')
const root=fs.mkdtempSync(path.join(os.tmpdir(),'atlas-core-')),bundle=path.join(root,'core.cjs')
const base=path.resolve('packages/ui/src/main/features')
buildSync({stdin:{resolveDir:process.cwd(),contents:['atlas-migrations','atlas-store','atlas-profile','atlas-tasks','atlas-export','atlas-backup','atlas-pipeline','atlas-import','career-workspace-service','atlas-server','atlas-ai'].map(f=>`export * from ${JSON.stringify(base+'/'+f+'.ts')}`).join('\n')},bundle:true,platform:'node',format:'cjs',outfile:bundle})
process.on('exit',()=>fs.rmSync(root,{recursive:true,force:true}))
function fixture(extra={}){const home=fs.mkdtempSync(path.join(root,'h-')),config=path.join(home,'.local/share/zhitu-atlas/config');fs.mkdirSync(config,{recursive:true});const m={exports:{}};vm.runInNewContext('(function(require,module,exports){'+fs.readFileSync(bundle,'utf8')+'\n})',{Buffer,process,Date,URL,fetch,AbortController,AbortSignal,setTimeout,clearTimeout,...extra})(k=>k==='node:os'?{homedir:()=>home}:require(k),m,m.exports);const api=m.exports,handlers=new Map();api.registerCareerWorkspace((k,f)=>handlers.set(k,f),()=>{});return{home,config,api,call:(k,v)=>handlers.get(k)({},v)}}
test('migration preserves originals and marks previously unconfirmed evidence explicitly',()=>{
 const f=fixture(),p={version:1,profile:{name:'候选人',headline:'产品负责人',summary:'企业平台',targetRoles:['AI产品负责人'],preferredCities:['上海'],minimumMonthlyK:40,evidence:[{title:'平台',text:'建设平台',keywords:['AI'],source:'旧资料'}],resumeText:'当前简历'},opportunities:[]}
 fs.writeFileSync(path.join(f.config,'career-workspace.json'),JSON.stringify(p));fs.writeFileSync(path.join(f.config,'resumes.json'),JSON.stringify([{content:{name:'旧名',userDescription:'旧文本'}}]))
 const original=fs.readFileSync(path.join(f.config,'career-workspace.json'),'utf8'),s=f.call('career-workspace-snapshot')
 assert.equal(s.state.profile.resumeText,'当前简历');assert.equal(s.state.profile.evidence[0].confirmed,false);assert.ok(s.state.profile.evidence[0].id)
 f.api.migrateProfile();assert.equal(f.api.profileHistory().length,1);assert.equal(fs.readFileSync(path.join(f.config,'career-workspace.json'),'utf8'),original)
 assert.equal(f.api.canonicalProfile().resumeText,'当前简历');f.api.closeAtlas()
})
test('workspace failure rolls back both data and profile version, restore creates a new version',()=>{
 const f=fixture();let s=f.call('career-workspace-snapshot');s.state.profile.resumeText='第一版简历';s=f.call('career-workspace-save',{state:JSON.stringify(s.state),baseRevision:s.revision})
 const first=f.api.profileHistory()[0]
 assert.throws(()=>f.api.atlasTransaction(()=>{f.api.atlasWrite('career-workspace.json',{...s.state,profile:{...s.state.profile,resumeText:'不得留下'}});throw Error('interrupted')}))
 assert.equal(f.api.canonicalProfile().resumeText,'第一版简历');assert.equal(f.api.profileHistory()[0].id,first.id)
 s.state.profile.resumeText='第二版简历';s=f.call('career-workspace-save',{state:JSON.stringify(s.state),baseRevision:s.revision})
 const restored=f.call('career-profile-restore',{id:first.id,baseRevision:s.revision});assert.equal(restored.state.profile.resumeText,'第一版简历');assert.notEqual(f.api.profileHistory()[0].id,first.id);f.api.closeAtlas()
})
test('Word export contains the same saved canonical resume and escapes XML',()=>{
 const f=fixture();const s=f.call('career-workspace-snapshot');s.state.profile.resumeText='候选人\n工作经历\n平台 <AI> & 数据产品';f.call('career-workspace-save',{state:JSON.stringify(s.state),baseRevision:s.revision})
 const out=f.call('career-profile-docx'),files=unzipSync(Buffer.from(out.base64,'base64')),xml=strFromU8(files['word/document.xml']);assert.match(xml,/&lt;AI&gt; &amp;/);assert.match(xml,/工作经历/);assert.ok(files['word/styles.xml']);f.api.closeAtlas()
})
test('pause, total quota, first-contact quota and cooldown apply across platforms',()=>{
 const f=fixture(),a={id:'one',platform:'boss',accountId:'u',recipientId:'b',kind:'first-contact',automatic:true,text:'您好'},now=Date.now()
 assert.match(f.api.claimSend(a,now),/暂停/)
 f.api.setRuntime({paused:false,dailyLimit:2,firstContactLimit:1,startHour:0,endHour:24})
 assert.equal(f.api.claimSend(a,now),'');assert.match(f.api.claimSend(a,now),/已有/)
 assert.match(f.api.claimSend({...a,id:'two',platform:'liepin'},now),/首条/)
 assert.equal(f.api.claimSend({...a,id:'reply',platform:'liepin',kind:'reply'},now),'');assert.match(f.api.claimSend({...a,id:'third',kind:'reply',recipientId:'c'},now),/合计/);f.api.closeAtlas()
})
test('two processes cannot own one browser lease or claim one message twice',async()=>{
 const f=fixture();f.api.setRuntime({paused:false,startHour:0,endHour:24});const owner=f.api.acquireLease('browser:boss:u');assert.ok(owner)
 const script=`const a=require(${JSON.stringify(bundle)}); const lease=a.acquireLease('browser:boss:u');const result=a.claimSend({id:'shared',platform:'boss',accountId:'u',recipientId:'b',kind:'reply',automatic:false,text:'test'});console.log(JSON.stringify({lease,result}));a.closeAtlas()`
 const run=()=>new Promise((resolve,reject)=>{const p=spawn(process.execPath,['-e',script],{env:{...process.env,ATLAS_DATA_ROOT:path.join(f.home,'.local/share/zhitu-atlas')}});let out='';p.stdout.on('data',d=>out+=d);p.on('exit',code=>code?reject(Error('child failed')):resolve(JSON.parse(out)))})
 const results=await Promise.all([run(),run()]);assert.equal(results.filter(r=>r.result==='').length,1);assert.ok(results.every(r=>r.lease===null));f.api.releaseLease('browser:boss:u',owner);assert.ok(f.api.acquireLease('browser:boss:u'));f.api.closeAtlas()
})
test('removed legacy commands stay removed after reopening the database',()=>{
 const f=fixture(),id='a'.repeat(64),key='career-reply-commands/'+id+'.json';fs.mkdirSync(path.join(f.config,'career-reply-commands'));fs.writeFileSync(path.join(f.config,key),JSON.stringify({id,action:'approve'}));assert.equal(f.api.atlasList('career-reply-commands').length,1);f.api.atlasRemove(key);f.api.closeAtlas();assert.equal(f.api.atlasList('career-reply-commands').length,0);f.api.closeAtlas()
})

test('encrypted migration rejects wrong passwords and corruption before changing live data',()=>{
 const f=fixture(),s=f.call('career-workspace-snapshot');s.state.profile.name='备份姓名';s.state.profile.resumeText='备份的简历';f.call('career-workspace-save',{state:JSON.stringify(s.state),baseRevision:s.revision})
 fs.writeFileSync(path.join(f.config,'llm.json'),JSON.stringify([{providerApiSecret:'PRIVATE_SECRET_NEVER_EXPORT'}]));f.api.setRuntime({paused:false})
 const backup=f.api.exportEncryptedBackup('strong-password-123'),clear=f.api.inspectBackup({password:'strong-password-123',base64:backup.base64})
 assert.ok(!JSON.stringify(clear).includes('PRIVATE_SECRET'));assert.throws(()=>f.api.inspectBackup({password:'wrong-password',base64:backup.base64}),/密码错误/)
 const tamper=Buffer.from(backup.base64,'base64');tamper[tamper.length-1]^=1;assert.throws(()=>f.api.inspectBackup({password:'strong-password-123',base64:tamper.toString('base64')}),/损坏/)
 assert.equal(f.api.canonicalProfile().name,'备份姓名');f.api.setRuntime({paused:true});const current=f.call('career-workspace-snapshot');current.state.profile.name='新姓名';f.call('career-workspace-save',{state:JSON.stringify(current.state),baseRevision:current.revision})
 f.api.restoreEncryptedBackup({password:'strong-password-123',base64:backup.base64,confirm:true});assert.equal(f.api.canonicalProfile().name,'备份姓名');assert.equal(f.api.runtimePolicy().paused,true);f.api.closeAtlas()
})
test('CSV import preserves quoting, blocks invalid rows, detects repeats and rejects stale confirmation',()=>{
 const f=fixture(),input={format:'csv',text:'公司名称,职位名称,职位描述,地址,月薪下限K,月薪上限K\n测试公司,AI产品经理,"需求,规划\n数据分析",上海,40,60'}
 let preview=f.api.previewImport(input);assert.equal(preview.newCount,1);assert.match(preview.rows[0].job.description,/需求,规划\n数据分析/)
 f.api.commitImport({...input,baseRevision:preview.revision});preview=f.api.previewImport(input);assert.equal(preview.duplicateCount,1);assert.equal(preview.newCount,0)
 const state=f.call('career-workspace-snapshot');state.state.profile.name='并发修改';f.call('career-workspace-save',{state:JSON.stringify(state.state),baseRevision:state.revision});assert.throws(()=>f.api.commitImport({...input,baseRevision:preview.revision}),/另一个窗口/);f.api.closeAtlas()
})
test('interviews, offers and tasks have optimistic revisions and stage transitions retain history',()=>{
 const f=fixture(),item={id:'manual:one',job:{companyName:'甲',jobName:'产品负责人'},stage:'已沟通',source:'manual'};f.api.indexOpportunity(item);f.api.indexOpportunity({...item,stage:'面试中'});let detail=f.api.saveRelated({opportunityId:item.id,kind:'interview',body:{title:'一面',date:'2026-10-01T10:00:00+08:00',note:'准备项目案例'}})
 assert.equal(detail.events.filter(e=>e.kind==='stage-change').length,1);const related=detail.related[0];f.api.saveRelated({id:related.id,opportunityId:item.id,kind:'interview',body:{...related.body,completed:true},baseRevision:related.revision});assert.throws(()=>f.api.saveRelated({id:related.id,opportunityId:item.id,kind:'interview',body:related.body,baseRevision:related.revision}),/已更新/);assert.equal(f.api.pipelineSummary().related[0].body.completed,true);f.api.closeAtlas()
})

test('versionless writes are rejected and changing confirmed facts revokes automatic use',()=>{
 const f=fixture();let s=f.call('career-workspace-snapshot');assert.throws(()=>f.call('career-workspace-save',JSON.stringify(s.state)),/版本/)
 s.state.profile.evidence=[{id:'confirmed',confirmed:true,title:'项目',text:'已核实的成果',keywords:['AI'],source:'本人'}];s=f.call('career-workspace-save',{state:JSON.stringify(s.state),baseRevision:s.revision});s.state.profile.evidence[0].text='新的成果';s=f.call('career-workspace-save',{state:JSON.stringify(s.state),baseRevision:s.revision});assert.equal(s.state.profile.evidence[0].confirmed,false);f.api.closeAtlas()
})
test('production loopback API requires its session, rejects foreign origins and shares native reads',async()=>{
 const f=fixture(),web=path.join(f.home,'web');fs.mkdirSync(web);fs.writeFileSync(path.join(web,'desktop.html'),'<head></head><body>Atlas</body>');const server=await f.api.startAtlasServer(web,0),base='http://127.0.0.1:'+server.address().port
 try{const page=await (await fetch(base+'/desktop.html')).text(),token=page.match(/name="atlas-session" content="([^"]+)"/)[1];assert.ok(token);const rpc=(headers={})=>fetch(base+'/atlas-api/rpc',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify({channel:'career-workspace-snapshot'})});assert.equal((await rpc()).status,403);assert.equal((await rpc({'X-Atlas-Token':token,Origin:'https://hostile.invalid'})).status,403);assert.equal((await rpc({'X-Atlas-Token':'é'.repeat(64)})).status,403);assert.equal((await rpc({'X-Atlas-Token':token})).status,200);const s=await f.api.invokeAtlas('career-workspace-snapshot');s.state.profile.name='两个入口同一个服务';await f.api.invokeAtlas('career-workspace-save',{state:JSON.stringify(s.state),baseRevision:s.revision});assert.equal(f.call('career-workspace-snapshot').state.profile.name,s.state.profile.name)}finally{await new Promise(r=>server.close(r));f.api.closeAtlas()}
})
test('restore retains attachments and old database, does not revive old approvals, and marks in-flight results uncertain',()=>{
 const f=fixture(),{DatabaseSync}=require('node:sqlite'),id='e'.repeat(64);f.call('career-workspace-snapshot');const old=new DatabaseSync(path.join(f.home,'.local/share/zhitu-atlas/storage/public.db'));old.exec('CREATE TABLE sample(id TEXT PRIMARY KEY);INSERT INTO sample VALUES("record")'.replace('"record"',"'record'"));old.close();const dir=path.join(f.home,'.local/share/zhitu-atlas/attachments');fs.mkdirSync(dir);fs.writeFileSync(path.join(dir,'resume.txt'),'附件内容');fs.mkdirSync(path.join(f.config,'career-reply-commands'));fs.writeFileSync(path.join(f.config,'career-reply-commands',id+'.json'),JSON.stringify({id,action:'approve',text:'旧批准'}));f.api.atlasWrite('career-replies/'+id+'.json',{id,status:'sending'});f.api.setRuntime({paused:false});assert.equal(f.api.claimSend({id,platform:'boss',accountId:'u',recipientId:'b',kind:'reply',automatic:false,text:'内容'}),'');const b=f.api.exportEncryptedBackup('backup-test-password');f.api.setRuntime({paused:true});f.api.restoreEncryptedBackup({password:'backup-test-password',base64:b.base64,confirm:true});assert.equal(f.api.atlasList('career-reply-commands').length,0);assert.equal(f.api.atlasList('career-replies')[0].status,'uncertain');assert.equal(f.api.taskSnapshot().sends[0].status,'uncertain');const attachments=f.api.atlasRead('atlas-restored-attachments');assert.equal(fs.readFileSync(path.join(f.home,'.local/share/zhitu-atlas',attachments.directory,'resume.txt'),'utf8'),'附件内容');const restored=new DatabaseSync(path.join(f.home,'.local/share/zhitu-atlas/storage',f.api.atlasRead('atlas-restored-legacy').file),{readOnly:true});assert.equal(restored.prepare('SELECT id FROM sample').get().id,'record');restored.close();f.api.closeAtlas()
})
test('DeepSeek cache keys change with evidence and invalid references cannot reach saved analyses',async()=>{
 let calls=0,invalid=false;const f=fixture({fetch:async()=>{calls++;return{ok:true,json:async()=>({choices:[{message:{content:JSON.stringify({businessGoal:'企业平台',requirements:[{requirement:'AI产品',evidenceIds:[invalid?'invented':'e1'],assessment:'可对应'}],strengths:['平台建设'],gaps:['待核实职责'],questions:['业务指标？'],draft:'您好',resumeSuggestions:['突出负责范围']})}}],usage:{total_tokens:30}})}}});fs.writeFileSync(path.join(f.config,'llm.json'),JSON.stringify([{enabled:true,model:'deepseek-flash',providerCompleteApiUrl:'https://api.deepseek.com',providerApiSecret:'test'}]));let s=f.call('career-workspace-snapshot');s.state.profile.evidence=[{id:'e1',confirmed:true,title:'平台',text:'负责平台',keywords:['AI'],source:'本人'}];s=f.call('career-workspace-save',{state:JSON.stringify(s.state),baseRevision:s.revision});const job={jobName:'AI产品经理',companyName:'企业',description:'负责AI企业产品建设与用户需求分析。'.repeat(10)};assert.equal((await f.api.analyzeJob({job})).cached,false);assert.equal((await f.api.analyzeJob({job})).cached,true);assert.equal(calls,1);s.state.profile.headline='企业产品';f.call('career-workspace-save',{state:JSON.stringify(s.state),baseRevision:s.revision});await f.api.analyzeJob({job});assert.equal(calls,2);invalid=true;await assert.rejects(f.api.analyzeJob({job,refresh:true}),/不存在的经历/);f.api.closeAtlas()
})

test('similar names remain separate until explicit merge, undo retains original relations and archive survives reindexing',()=>{
 const f=fixture(),a={id:'manual:a',job:{companyName:'同名公司',jobName:'产品经理'},stage:'待评估',source:'来源甲'},b={...a,id:'manual:b',source:'来源乙'};f.api.indexOpportunity(a);f.api.indexOpportunity(b);let da=f.api.pipelineDetail(a.id),db=f.api.pipelineDetail(b.id);assert.equal(da.candidates.length,1);assert.equal(da.body.mergedInto,'');f.api.saveRelated({opportunityId:a.id,kind:'todo',body:{title:'保留来源甲待办'}});da=f.api.pipelineDetail(a.id);const merged=f.api.mergeOpportunity({id:a.id,targetId:b.id,baseRevision:da.revision,targetRevision:db.revision});assert.equal(merged.related.length,1);assert.equal(merged.related[0].opportunity_id,a.id);da=f.api.pipelineDetail(a.id);f.api.undoMerge({id:a.id,baseRevision:da.revision});assert.equal(f.api.pipelineDetail(b.id).related.length,0);assert.equal(f.api.pipelineDetail(a.id).related.length,1);da=f.api.pipelineDetail(a.id);f.api.setArchived({id:a.id,baseRevision:da.revision,archived:true});f.api.indexOpportunity(a);assert.equal(f.api.pipelineStates()[a.id].archived,true);f.api.closeAtlas()
})

test('restoring identical contents still invalidates older editor revisions',()=>{
 const f=fixture();let a=f.call('career-workspace-snapshot');a.state.profile.name='初始';a=f.call('career-workspace-save',{state:JSON.stringify(a.state),baseRevision:a.revision});const originalVersion=f.api.profileHistory()[0],stale=structuredClone(a);a.state.profile.name='后来';a=f.call('career-workspace-save',{state:JSON.stringify(a.state),baseRevision:a.revision});const restored=f.call('career-profile-restore',{id:originalVersion.id,baseRevision:a.revision});assert.equal(restored.state.profile.name,stale.state.profile.name);assert.notEqual(restored.revision,stale.revision);assert.throws(()=>f.call('career-workspace-save',{state:JSON.stringify(stale.state),baseRevision:stale.revision}),/另一个窗口/);f.api.closeAtlas()
})
test('source imports deduplicate changed JDs per platform and account and report malformed rows',()=>{
 const f=fixture(),v={platform:'boss',accountId:'alice',sourceId:'j1',jobName:'AI产品负责人',companyName:'公司',description:'原始JD'},input={format:'json',text:JSON.stringify([v])};const p=f.api.previewImport(input);f.api.commitImport({...input,baseRevision:p.revision});const p2=f.api.previewImport({format:'json',text:JSON.stringify([{...v,description:'更改JD'},{...v,accountId:'bob'},{...v,platform:'liepin'},null,{jobName:123,companyName:'企业'}])});assert.equal(p2.duplicateCount,1);assert.equal(p2.newCount,2);assert.equal(p2.errors.length,2);f.api.closeAtlas()
})
test('expired interrupted sends become uncertain and explicit resolution cannot revive sending',()=>{
 const f=fixture(),now=Date.now();f.api.setRuntime({paused:false});const a={id:'interrupted',platform:'boss',accountId:'u',recipientId:'b',kind:'reply',automatic:false,text:'消息'};assert.equal(f.api.claimSend(a,now-120000),'');const lease=f.api.acquireLease('browser:boss:u');f.api.recoverAbandonedSends(now);assert.equal(f.api.taskSnapshot().sends[0].status,'sending');f.api.releaseLease('browser:boss:u',lease);f.api.recoverAbandonedSends(now);const row=f.api.taskSnapshot().sends[0];assert.equal(row.status,'uncertain');f.api.resolveSend({id:a.id,result:'not-sent',updatedAt:row.updated_at});assert.equal(f.api.taskSnapshot().sends[0].status,'cancelled');assert.match(f.api.claimSend(a,now),/已有/);f.api.closeAtlas()
})
test('duplicate evidence ids and non-boolean confirmations are rejected',()=>{
 const f=fixture(),s=f.call('career-workspace-snapshot'),e={id:'one',confirmed:true,title:'项目',text:'内容',keywords:[],source:'本人'};s.state.profile.evidence=[e,{...e}];assert.throws(()=>f.call('career-workspace-save',{state:JSON.stringify(s.state),baseRevision:s.revision}),/格式/);s.state.profile.evidence=[{...e,confirmed:'false'}];assert.throws(()=>f.call('career-workspace-save',{state:JSON.stringify(s.state),baseRevision:s.revision}),/格式/);f.api.closeAtlas()
})
test('offer comparison preserves unknown components and rejects negative pay',()=>{
 const f=fixture(),id='manual:offer';f.api.indexOpportunity({id,job:{companyName:'甲',jobName:'产品'},stage:'Offer',source:'manual'});f.api.saveRelated({opportunityId:id,kind:'offer',body:{title:'Offer A',monthlyK:40,salaryMonths:13}});let summary=f.api.pipelineSummary();assert.equal(summary.offers[0].fixedAnnualK,520);assert.equal(summary.offers[0].totalAnnualK,null);assert.throws(()=>f.api.saveRelated({opportunityId:id,kind:'offer',body:{title:'无效',monthlyK:-1}}),/薪资|金额|Offer/);f.api.closeAtlas()
})

test('full restore rolls back a validly encrypted but relationally broken archive',()=>{
 const f=fixture(),crypto=require('node:crypto'),zlib=require('node:zlib'),password='restore-failure-test';let s=f.call('career-workspace-snapshot');s.state.profile.name='原数据不可覆盖';f.call('career-workspace-save',{state:JSON.stringify(s.state),baseRevision:s.revision});f.api.setRuntime({paused:true,dailyLimit:7,firstContactLimit:3});const backup=f.api.exportEncryptedBackup(password),archive=f.api.inspectBackup({password,base64:backup.base64});archive.tables.profile_versions.push({...archive.tables.profile_versions[0]});const salt=crypto.randomBytes(16),iv=crypto.randomBytes(12),key=crypto.scryptSync(password,salt,32,{N:32768,r:8,p:1,maxmem:64*1024*1024}),cipher=crypto.createCipheriv('aes-256-gcm',key,iv),data=Buffer.concat([cipher.update(zlib.gzipSync(Buffer.from(JSON.stringify(archive)))),cipher.final()]),base64=Buffer.concat([Buffer.from('ATLASBK1'),salt,iv,cipher.getAuthTag(),data]).toString('base64');assert.throws(()=>f.api.restoreEncryptedBackup({password,base64,confirm:true}));assert.equal(f.api.canonicalProfile().name,'原数据不可覆盖');const before=f.call('career-workspace-snapshot');f.api.restoreEncryptedBackup({password,base64:backup.base64,confirm:true});assert.equal(f.api.runtimePolicy().dailyLimit,7);assert.equal(f.api.runtimePolicy().paused,true);assert.notEqual(before.revision,f.call('career-workspace-snapshot').revision);assert.equal(f.api.atlasRead('atlas-restored-legacy').disabled,true);f.api.closeAtlas()
})
test('task policy updates reject stale revisions without changing the current policy',async()=>{
 const f=fixture(),web=path.join(f.home,'web');fs.mkdirSync(web);fs.writeFileSync(path.join(web,'desktop.html'),'<head></head>');const server=await f.api.startAtlasServer(web,0);try{const before=await f.api.invokeAtlas('career-tasks-load');await f.api.invokeAtlas('career-tasks-policy',{policy:{...before.policy,dailyLimit:18},baseRevision:before.policyRevision});await assert.rejects(f.api.invokeAtlas('career-tasks-policy',{policy:{...before.policy,dailyLimit:25},baseRevision:before.policyRevision}),/另一个窗口/);assert.equal(f.api.runtimePolicy().dailyLimit,18);assert.equal(f.api.runtimePolicy().paused,true)}finally{await new Promise(r=>server.close(r));f.api.closeAtlas()}
})


test('schema migrations are ordered, repeatable and reject a future database without removing records',()=>{
 const f=fixture(),db=f.api.atlasDb();assert.equal(db.prepare('SELECT MAX(version) n FROM atlas_migrations').get().n,f.api.atlasSchemaVersion);f.api.migrateAtlasSchema(db);assert.equal(db.prepare('SELECT COUNT(*) n FROM atlas_migrations').get().n,f.api.atlasSchemaVersion);db.prepare("INSERT INTO documents VALUES('atlas-check','true',1,'now')").run();db.prepare("INSERT INTO atlas_migrations VALUES(?,'future')").run(f.api.atlasSchemaVersion+1);assert.throws(()=>f.api.migrateAtlasSchema(db),/版本较新/);assert.equal(db.prepare("SELECT value FROM documents WHERE key='atlas-check'").get().value,'true');assert.equal(db.prepare('SELECT COUNT(*) n FROM atlas_migrations').get().n,f.api.atlasSchemaVersion+1);f.api.closeAtlas()
})
test('an interrupted migration rolls back DDL and the journal together',()=>{
 const f=fixture(),db=f.api.atlasDb();db.exec('DROP TABLE execution_subjects; DROP TABLE execution_events; DROP TABLE execution_links; DROP TABLE execution_steps; DROP TABLE execution_runs; DROP TABLE contact_runs; DROP TABLE contact_reservations; DROP TABLE job_observations; DROP INDEX contact_messages; ALTER TABLE send_attempts DROP COLUMN context; ALTER TABLE send_attempts DROP COLUMN proof; DROP TABLE task_runs; DROP TABLE legacy_records; DROP TABLE ai_calls; DROP INDEX sends_conversation; DROP TABLE platform_jobs; DROP TABLE platform_conversations; DROP TABLE platform_messages; DROP TABLE platform_job_history; DELETE FROM atlas_migrations WHERE version>=2');const broken={prepare:db.prepare.bind(db),exec:sql=>{db.exec(sql);if(sql.includes('CREATE INDEX IF NOT EXISTS sends_conversation'))throw Error('simulated interruption')}};assert.throws(()=>f.api.migrateAtlasSchema(broken),/interruption/);assert.equal(db.prepare('SELECT MAX(version) n FROM atlas_migrations').get().n,1);assert.equal(db.prepare("SELECT name FROM sqlite_master WHERE type='index' AND name='sends_conversation'").get(),undefined);f.api.migrateAtlasSchema(db);assert.equal(db.prepare('SELECT MAX(version) n FROM atlas_migrations').get().n,f.api.atlasSchemaVersion);f.api.closeAtlas()
})
test('map origins reject concurrent saves while leaving the newer point intact',async()=>{
 const f=fixture(),web=path.join(f.home,'web');fs.mkdirSync(web);fs.writeFileSync(path.join(web,'desktop.html'),'<head></head>');const server=await f.api.startAtlasServer(web,0);try{const first=await f.api.invokeAtlas('career-map-origin');const saved=await f.api.invokeAtlas('career-map-origin-save',{value:{lat:31.2,lng:121.5},baseRevision:first.revision});assert.equal(saved.value.crs,'wgs84');await assert.rejects(f.api.invokeAtlas('career-map-origin-save',{value:{lat:31.1,lng:121.4},baseRevision:first.revision}),/另一个窗口/);assert.equal((await f.api.invokeAtlas('career-map-origin')).value.lng,121.5)}finally{await new Promise(r=>server.close(r));f.api.closeAtlas()}
})

test('discovery analysis requests an explicit investment decision in its final schema', async()=>{
 let schema='';const f=fixture({fetch:async(_url,options)=>{schema=JSON.parse(options.body).messages[0].content.split('仅输出 JSON')[1];return {ok:true,json:async()=>({choices:[{message:{content:JSON.stringify({recommendation:{decision:'verify',reason:'学历未确认',nextStep:'先确认学历'},businessGoal:'平台建设',requirements:[{requirement:'产品经验',evidenceIds:['e1'],assessment:'待本人确认',status:'verify',essential:true}],strengths:[],gaps:['学历'],questions:['学历情况'],draft:'',resumeSuggestions:[]})}}],usage:{total_tokens:20}})}}});
 fs.writeFileSync(path.join(f.config,'llm.json'),JSON.stringify([{enabled:true,model:'deepseek-flash',providerCompleteApiUrl:'https://api.deepseek.com',providerApiSecret:'test'}]));let s=f.call('career-workspace-snapshot');s.state.profile.evidence=[{id:'e1',confirmed:false,title:'平台',text:'负责平台',keywords:['AI'],source:'本人待确认'}];f.call('career-workspace-save',{state:JSON.stringify(s.state),baseRevision:s.revision});
 const result=await f.api.analyzeJob({mode:'discovery',job:{jobName:'AI产品经理',description:'负责AI企业产品建设与用户需求分析。'.repeat(10)}});assert.match(schema,/recommendation:\{decision:prioritize\|consider\|verify\|skip/);assert.equal(result.analysis.recommendation.reason,'学历未确认');assert.equal(f.api.canonicalProfile().evidence[0].confirmed,false);f.api.closeAtlas();
});
