const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),vm=require('node:vm'),{EventEmitter}=require('node:events'),{buildSync}=require('esbuild')
const root=fs.mkdtempSync(path.join(os.tmpdir(),'atlas-sync-')),bundle=path.join(root,'sync.cjs'),features=path.resolve('packages/ui/src/main/features')
buildSync({stdin:{resolveDir:process.cwd(),contents:['atlas-store','atlas-migrations','atlas-boss-sync','career-boss-data','atlas-service','atlas-backup','atlas-boss-capture','career-data-sync','atlas-boss-navigation','atlas-boss-account-state'].map(n=>`export * from ${JSON.stringify(features+'/'+n+'.ts')}`).join('\n')+'\nexport * from '+JSON.stringify(path.resolve('packages/ui/src/common/boss-sync.ts'))},bundle:true,platform:'node',format:'cjs',outfile:bundle})
process.on('exit',()=>fs.rmSync(root,{recursive:true,force:true}))
function fixture(){const home=fs.mkdtempSync(path.join(root,'home-')),m={exports:{}};vm.runInNewContext('(function(require,module,exports){'+fs.readFileSync(bundle,'utf8')+'\n})',{Buffer,process,Date,URL,fetch,AbortController,AbortSignal,setTimeout,clearTimeout,setInterval,clearInterval})(k=>k==='node:os'?{homedir:()=>home}:require(k),m,m.exports);const a=m.exports,handlers=a.createAtlasHandlers(async()=>({data:{applications:[],databaseAvailable:true}}));return{a,home,call:(name,payload)=>handlers.get(name)({},payload)}}
const stamp=Date.now()-10000
const contact=(boss='b',job='j',extra={})=>({bossId:boss,bossName:'联系人',companyName:'企业',encryptJobId:job,...extra})
const snap=(account='a',items=[contact()],conversation)=>({account:{id:account,name:'测试账号'},items,conversation})
const msg=(mid,isSelf,text,time=stamp)=>({mid,isSelf,text,type:'text',time,status:2})
const convo=(messages,extra={})=>({bossId:'b',identityVerified:true,messages,...extra})
const job=(extra={})=>({code:0,zpData:{jobInfo:{encryptId:'j',jobName:'AI产品负责人',postDescription:'负责企业AI产品规划与落地，搭建可复用技能平台。',address:'上海市徐汇区',salaryDesc:'40-60K·14薪',...extra},bossInfo:{encryptBossId:'b',name:'联系人',activeTimeDesc:'刚刚活跃'},brandComInfo:{encryptBrandId:'company',brandName:'企业',stageName:'B轮',industryName:'软件'}}})
const detailPath='/wapi/zpgeek/job/detail.json'

test('known job ids gain real details without inventing missing salary or coordinates',()=>{const f=fixture(),a=f.a;a.saveBossSnapshot(snap());assert.equal(a.bossSyncCoverage().descriptions,0);a.ingestBossJobs('a',job(),detailPath);const coverage=a.bossSyncCoverage();assert.equal(coverage.linkedDetails,1);assert.equal(coverage.salaries,1);assert.equal(coverage.addresses,1);const rows=a.enrichSyncedRecords({applications:[],jobLibrary:[]},a.readBossSync()).applications;assert.equal(rows[0].jobName,'AI产品负责人');assert.equal(rows[0].salaryMonth,14);assert.equal(rows[0].lng,undefined);assert.equal(rows[0].firstContact,'');assert.equal(a.bossSalary('面议').salaryLow,undefined);assert.equal(a.bossSalary('200-300元/天').salaryHigh,undefined);assert.equal(a.bossSalary('60-40K').salaryHigh,undefined);a.closeAtlas()})
test('one contact retains several jobs and switching back restores the account index',()=>{const {a}=fixture();a.saveBossSnapshot(snap());a.saveBossSnapshot(snap('a',[contact('b','j2')]));assert.equal(a.readBossSync().items.length,2);a.saveBossSnapshot(snap('other',[]));assert.equal(a.bossSyncCoverage().conversations,0);a.saveBossSnapshot(snap('a',[]));assert.equal(a.readBossSync().items.length,2);assert.equal(a.listBossConversations().items.length,1);a.closeAtlas()})
test('messages deduplicate across restart, retain read state and isolate accounts and conversations',()=>{const {a}=fixture();a.saveBossSnapshot(snap('a',[contact()],convo([msg('1',false,'您好'),msg('2',true,'您好')])));a.closeAtlas();a.saveBossSnapshot(snap('a',[contact()],convo([msg('1',false,'您好'),msg('2',true,'您好')])));assert.equal(a.bossConversationDetail({accountId:'a',bossId:'b'}).total,2);a.saveBossSnapshot(snap('other',[contact()],convo([msg('1',false,'另一个账号消息')])));assert.equal(a.bossSyncCoverage().messages,1);assert.throws(()=>a.bossConversationDetail({accountId:'a',bossId:'b'}),/账号已变化/);a.saveBossSnapshot(snap('a',[],convo([msg('1',true,'错误方向')])));assert.equal(a.bossConversationDetail({accountId:'a',bossId:'b'}).messages.find(m=>m.id==='1').text,'您好');a.closeAtlas()})
test('identity mismatch and unstable message ids cannot populate the timeline',()=>{const {a}=fixture();a.saveBossSnapshot(snap('a',[contact()],convo([msg('1',false,'错误会话')],{identityVerified:false})));assert.equal(a.bossSyncCoverage().messages,0);a.saveBossSnapshot(snap('a',[contact()],convo([msg(undefined,false,'没有ID'),msg(Number.MAX_SAFE_INTEGER+1,false,'不精确ID'),msg('ok',false,'已确认消息')])));assert.equal(a.bossSyncCoverage().messages,1);assert.equal(a.bossConversationDetail({accountId:'a',bossId:'b'}).body.skippedMessageCount,2);a.closeAtlas()})
test('late job responses and unexpected endpoint payloads do not cross account boundaries',()=>{const {a}=fixture();a.saveBossSnapshot(snap('a'));a.saveBossSnapshot(snap('b'));assert.equal(a.ingestBossJobs('a',job(),detailPath).saved,0);assert.equal(a.ingestBossJobs('b',{code:0,zpData:{changed:true}},detailPath).reason,'schema-changed');assert.equal(a.ingestBossJobs('b',job(),'/wapi/unexpected').saved,0);assert.equal(a.bossCapturePath('https://www.zhipin.com.attacker.invalid'+detailPath),'');assert.equal(a.bossCapturePath('https://www.zhipin.com'+detailPath+'?securityId=private'),detailPath);a.closeAtlas()})
test('job snapshots preserve real A-B-A changes but ignore activity-only changes and list summaries',()=>{const {a}=fixture();a.saveBossSnapshot(snap());const p=job();a.ingestBossJobs('a',p,detailPath);p.zpData.bossInfo.activeTimeDesc='今日活跃';a.ingestBossJobs('a',p,detailPath);assert.equal(a.bossJobHistory({accountId:'a',jobId:'j'}).length,1);a.ingestBossJobs('a',job({salaryDesc:'45-60K·15薪'}),detailPath);a.ingestBossJobs('a',job(),detailPath);assert.equal(a.bossJobHistory({accountId:'a',jobId:'j'}).length,3);a.ingestBossJobs('a',{code:0,zpData:{jobList:[{encryptJobId:'j',jobName:'列表简称',salaryDesc:'面议'}]}},'/wapi/zpgeek/search/joblist.json');assert.equal(a.capturedBossJobs()[0].salaryLow,40);assert.equal(a.capturedBossJobs()[0].jobName,'AI产品负责人');a.closeAtlas()})
test('observed search candidates stay in discovery and are not counted as contacted',()=>{const {a}=fixture();a.saveBossSnapshot(snap('a',[]));a.ingestBossJobs('a',{code:0,zpData:{jobList:[{encryptJobId:'j',jobName:'产品经理',brandName:'企业'}]}},'/wapi/zpgeek/search/joblist.json');const records=a.enrichSyncedRecords({applications:[],jobLibrary:[]},a.readBossSync()).applications;assert.equal(records.length,0);assert.equal(a.capturedBossJobs().length,1);assert.equal(a.bossSyncCoverage().conversations,0);a.closeAtlas()})
test('priority uses observed direction and important requests without promoting unknown messages',()=>{const {a}=fixture();a.saveBossSnapshot(snap('a',[contact('waiting','j1',{lastText:'面试几点',lastIsSelf:true}),contact('urgent','j2',{lastText:'明天方便面试吗',lastIsSelf:false}),contact('normal','j3',{lastText:'你好',lastIsSelf:false,unreadCount:0}),contact('unknown','j4')]));const list=a.listBossConversations();assert.equal(list.items[0].bossId,'urgent');assert.equal(list.items[1].bossId,'normal');assert.equal(list.counts.waiting,1);assert.equal(list.counts.unknown,1);a.saveBossSnapshot(snap('a',[contact('normal','j3',{unreadCount:0})]));assert.equal(a.listBossConversations({filter:'reply'}).total,1);a.closeAtlas()})
test('timeline pagination keeps duplicate timestamps stable and unknown time explicit',()=>{const {a}=fixture();a.saveBossSnapshot(snap('a',[contact()],convo(Array.from({length:125},(_,i)=>msg(String(i).padStart(4,'0'),false,'消息'+i,i===0?0:stamp)))));const first=a.bossConversationDetail({accountId:'a',bossId:'b',page:1}),second=a.bossConversationDetail({accountId:'a',bossId:'b',page:2});assert.equal(first.messages.length,50);assert.equal(second.messages.length,50);assert.equal(new Set([...first.messages,...second.messages].map(m=>m.id)).size,100);const last=a.bossConversationDetail({accountId:'a',bossId:'b',page:3});assert.equal(last.messages.find(m=>m.id==='0000').sentAt,'');a.closeAtlas()})
test('communication sample rate requires an observed response after outbound and has an explicit denominator',()=>{const {a}=fixture();a.saveBossSnapshot(snap('a',[contact()],convo([msg('before',false,'先前收到的消息',stamp-1000),msg('out',true,'您好',stamp)])));assert.equal(a.bossCommunicationMetrics().textReplyRate,0);a.saveBossSnapshot(snap('a',[],convo([msg('after',false,'方便聊聊',stamp+1000)])));const metrics=a.bossCommunicationMetrics();assert.equal(metrics.outboundConversations,1);assert.equal(metrics.textReplyConversations,1);assert.equal(metrics.textReplyRate,100);assert.match(metrics.definition,/可见样本/);a.closeAtlas()})
test('encrypted migration carries captured jobs and messages',()=>{const f=fixture(),a=f.a;f.call('career-workspace-snapshot');a.saveBossSnapshot(snap('a',[contact()],convo([msg('1',false,'消息')])));a.ingestBossJobs('a',job(),detailPath);const b=a.exportEncryptedBackup('test-password-123'),old=a.inspectBackup({password:'test-password-123',base64:b.base64});assert.equal(old.tables.platform_messages.length,1);a.restoreEncryptedBackup({password:'test-password-123',base64:b.base64,confirm:true});a.closeAtlas();assert.equal(a.bossSyncCoverage().messages,1);assert.equal(a.bossSyncCoverage().linkedDetails,1);assert.equal(a.atlasDb().prepare('select max(version) n from atlas_migrations').get().n,a.atlasSchemaVersion);a.closeAtlas()})
test('restoring a schema-2 archive preserves current schema and does not replay migrations',()=>{const f=fixture(),a=f.a,password='old-backup-password';f.call('career-workspace-snapshot');const b=a.exportEncryptedBackup(password),archive=a.inspectBackup({password,base64:b.base64});archive.tables.atlas_migrations=archive.tables.atlas_migrations.filter(r=>r.version<=2);for(const key of Object.keys(archive.tables))if(key.startsWith('platform_'))delete archive.tables[key];const {randomBytes,scryptSync,createCipheriv}=require('node:crypto'),{gzipSync}=require('node:zlib'),salt=randomBytes(16),iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',scryptSync(password,salt,32,{N:32768,r:8,p:1,maxmem:64*1024*1024}),iv),encrypted=Buffer.concat([cipher.update(gzipSync(Buffer.from(JSON.stringify(archive)))),cipher.final()]),base64=Buffer.concat([Buffer.from('ATLASBK1'),salt,iv,cipher.getAuthTag(),encrypted]).toString('base64');a.restoreEncryptedBackup({password,base64,confirm:true});a.closeAtlas();assert.equal(a.atlasDb().prepare('select max(version) n from atlas_migrations').get().n,a.atlasSchemaVersion);assert.equal(a.bossSyncCoverage().messages,0);a.closeAtlas()})
test('per-opportunity drafts retain content on concurrent revision conflicts',async()=>{const f=fixture(),a=f.a;f.call('career-workspace-snapshot');a.saveBossSnapshot(snap());await f.call('career-dashboard-load');const id='boss:a:job:j',left=f.call('career-opportunity-draft-load',{id}),right=f.call('career-opportunity-draft-load',{id});f.call('career-opportunity-draft-save',{id,text:'已保存招呼',basis:'v1',baseRevision:left.revision});assert.throws(()=>f.call('career-opportunity-draft-save',{id,text:'旧窗口',basis:'v1',baseRevision:right.revision}),/另一个窗口/);assert.equal(f.call('career-opportunity-draft-load',{id}).value.text,'已保存招呼');a.closeAtlas()})
test('passive native transport captures only allowlisted response bodies and tolerates account changes',async()=>{const {a}=fixture();a.saveBossSnapshot(snap());const debuggerApi=new EventEmitter(),calls=[];let account='a',epoch=1;debuggerApi.isAttached=()=>false;debuggerApi.attach=()=>{};debuggerApi.detach=()=>{};debuggerApi.sendCommand=async(method)=>{calls.push(method);return method==='Network.getResponseBody'?{body:JSON.stringify(job())}:{}};const wc={debugger:debuggerApi,isDestroyed:()=>false},capture=a.attachBossResponseCapture(wc,async()=>({id:account,epoch}),async()=>{}),emit=async(method,p)=>{for(const fn of debuggerApi.listeners('message'))await fn({},method,p)};await emit('Network.responseReceived',{requestId:'r',type:'Fetch',response:{url:'https://www.zhipin.com'+detailPath,status:200}});await emit('Network.loadingFinished',{requestId:'r',encodedDataLength:2000});assert.equal(a.bossSyncCoverage().linkedDetails,1);await emit('Network.responseReceived',{requestId:'s',type:'Fetch',response:{url:'https://www.zhipin.com/wapi/private/profile',status:200}});await emit('Network.loadingFinished',{requestId:'s'});assert.equal(calls.filter(x=>x==='Network.getResponseBody').length,1);await emit('Network.responseReceived',{requestId:'t',type:'Fetch',response:{url:'https://www.zhipin.com'+detailPath,status:200}});account='other';epoch++;a.saveBossSnapshot(snap('other',[]));await emit('Network.loadingFinished',{requestId:'t'});assert.equal(a.bossSyncCoverage().observedJobs,0);assert.equal(calls.filter(x=>x==='Network.getResponseBody').length,1);capture.dispose();assert.equal(debuggerApi.listenerCount('message'),0);a.closeAtlas()})

test('unread filter includes important and routine messages regardless of their priority bucket',()=>{const {a}=fixture();a.saveBossSnapshot(snap('a',[contact('urgent','j1',{lastText:'方便面试吗',lastIsSelf:false,unreadCount:1}),contact('routine','j2',{lastText:'你好',lastIsSelf:false,unreadCount:2}),contact('only-unread','j3',{unreadCount:1}),contact('read','j4',{lastText:'你好',lastIsSelf:false,unreadCount:0})]));const list=a.listBossConversations({filter:'unread'});assert.equal(list.counts.unread,3);assert.equal(list.total,3);assert.deepEqual(new Set(list.items.map(r=>r.bossId)),new Set(['urgent','routine','only-unread']));assert.equal(list.items[0].bossId,'urgent');a.closeAtlas()})
test('platform resume receipts do not become pending recruiter requests',()=>{const {a}=fixture();for(const text of ['您的附件简历 产品-董正... 已发送给Boss点击查看附件','对方已同意，您的附件简历已发送给对方']){assert.equal(a.conversationPriority({lastText:text,lastIsSelf:false,unreadCount:0}).bucket,'unknown');assert.equal(a.conversationPriority({lastText:text,lastIsSelf:false,unreadCount:1}).bucket,'unread')}assert.equal(a.conversationPriority({lastText:'方便发一份附件简历吗',lastIsSelf:false}).bucket,'important');a.closeAtlas()})

test('rendered job detail uses its own account context and only whitelisted fields',()=>{const {a}=fixture(),detail={data:job().zpData,$store:{state:{userInfo:{encryptUserId:'detail-account',name:'用户'}}}};detail.data.jobInfo.privateToken='never-copy';const selectors={'.job-detail-box':{__vue__:detail}},document={querySelector:s=>selectors[s]||null,querySelectorAll:()=>[]};const result=vm.runInNewContext('('+a.readBossPageSnapshot.toString()+')()',{document});assert.equal(result.account.id,'detail-account');assert.equal(result.jobDetail.jobInfo.encryptId,'j');assert.equal(result.jobDetail.jobInfo.privateToken,undefined);assert.equal(result.items.length,0);a.closeAtlas()})
test('an explicit rejection is not queued as a request for a resume',()=>{const {a}=fixture();const p=a.conversationPriority({lastIsSelf:false,lastText:'很抱歉，您的简历和我们当前的职位需求不是很匹配。祝您找到满意的工作！'});assert.equal(p.bucket,'unknown');assert.equal(p.label,'对方婉拒');a.closeAtlas()})
test('standalone public job address can enrich only an exact existing source ID',()=>{const {a}=fixture();a.saveBossSnapshot(snap());const observed={...job().zpData,sourceKind:'rendered-public-job',pageUrl:'https://www.zhipin.com/job_detail/j.html'};assert.equal(a.ingestBossPublicJobs([observed]).saved,1);assert.equal(a.bossSyncCoverage().addresses,1);observed.jobInfo.encryptId='unknown';observed.pageUrl='https://www.zhipin.com/job_detail/unknown.html';assert.equal(a.ingestBossPublicJobs([observed]).saved,0);assert.equal(a.capturedBossJobs().length,1);assert.equal(a.readBossSync().account.id,'a');a.closeAtlas()})
test('standalone document address reader distinguishes URL identity and multiple work sites',()=>{const {a}=fixture(),nodes=[{getAttribute:()=> '上海市长宁区福泉北路'}],document={location:{pathname:'/job_detail/j.html',hostname:'www.zhipin.com'},defaultView:{_jobInfo:{job_id:'j'}},querySelector:()=>null,querySelectorAll:s=>s.includes('job-location')?nodes:[]};const read=()=>vm.runInNewContext('('+a.readBossPageSnapshot.toString()+')()',{document});assert.equal(read().publicJobs[0].jobInfo.address,'上海市长宁区福泉北路');nodes.push({getAttribute:()=> '上海市徐汇区漕河泾'});assert.equal(read().publicJobs[0].jobInfo.address,'');assert.equal(read().publicJobs[0].jobInfo.workAddresses.length,2);document.defaultView._jobInfo.job_id='other';assert.equal(read().publicJobs.length,0);a.closeAtlas()})

test('navigation records actual page changes without security parameters and caps history',()=>{const {a}=fixture();a.recordBossNavigation('https://www.zhipin.com/job_detail/j.html?securityId=secret#fragment');assert.equal(a.readBossNavigation().current.url,'https://www.zhipin.com/job_detail/j.html');assert.equal(a.readBossNavigation().current.jobId,'j');a.recordBossNavigation('https://www.zhipin.com/job_detail/j.html?securityId=changed');assert.equal(a.readBossNavigation().history.length,1);a.recordBossNavigation('https://attacker.invalid/job_detail/j.html');assert.equal(a.readBossNavigation().history.length,1);for(let i=0;i<105;i++)a.recordBossNavigation('https://www.zhipin.com/job_detail/job-'+i+'.html');assert.equal(a.readBossNavigation().history.length,100);a.closeAtlas()})


test('virtualized contact store includes rows outside the visible viewport',()=>{const {a}=fixture();const all=Array.from({length:60},(_,i)=>({encryptBossId:'boss-'+i,name:'联系人'+i,encryptJobId:'j'+i}));const document={querySelector:s=>s==='.main-wrap'?{__vue__:{$store:{state:{userInfo:{encryptUserId:'a'}}}}}:s==='.main-wrap .chat-user'?{__vue__:{list:all}}:null,querySelectorAll:()=>[]};const result=vm.runInNewContext('('+a.readBossPageSnapshot.toString()+')()',{document});assert.equal(result.items.length,60);assert.equal(result.listSource,'loaded-store');assert.equal(result.listFinished,false);a.closeAtlas()})
test('local alerts survive collector read receipts and acknowledge only the observed summary',()=>{const {a,call}=fixture();a.saveBossSnapshot(snap('a',[contact('b','j',{lastText:'方便面试吗',lastIsSelf:false,unreadCount:2,updateTime:stamp})]));let c=a.listBossConversations().items[0];const first=c.atlasAlertKey;assert.equal(c.atlasUnreadCount,2);a.saveBossSnapshot({...snap('a',[contact('b','j',{lastText:'方便面试吗',lastIsSelf:false,unreadCount:0,updateTime:stamp})]),collector:true});assert.equal(a.listBossConversations({filter:'attention'}).total,1);a.saveBossSnapshot(snap('a',[contact('b','j',{lastText:'新的消息',unreadCount:1,updateTime:stamp+500})]));call('career-boss-conversation-ack',{accountId:'a',bossId:'b',alertKey:first});c=a.listBossConversations().items[0];assert.equal(c.atlasUnreadCount,1);call('career-boss-conversation-ack',{accountId:'a',bossId:'b',alertKey:c.atlasAlertKey});assert.equal(a.listBossConversations({filter:'attention'}).total,0);assert.throws(()=>call('career-boss-conversation-ack',{accountId:'other',bossId:'b'}),/账号/);a.closeAtlas()})
test('automatic sync state is account scoped and controls persist without altering send pause',()=>{const {a,call}=fixture();a.saveBossSnapshot(snap());a.updateAccountSync('a',{state:'syncing',visited:3});assert.equal(a.bossSyncCoverage().automatic.visited,3);a.saveBossSnapshot(snap('other',[]));assert.equal(a.bossSyncCoverage().automatic.visited,undefined);call('career-boss-sync-control',{enabled:false});assert.equal(a.bossSyncCoverage().automatic.state,'paused');assert.throws(()=>call('career-boss-sync-control',{enabled:'true'}),/无效/);a.closeAtlas()})
test('encrypted migration never resumes automatic reading or carries collector runtime',()=>{const {a,call}=fixture();call('career-workspace-snapshot');a.saveBossSnapshot(snap());a.updateAccountSync('a',{state:'syncing',visited:10});call('career-boss-sync-control',{enabled:true});const b=a.exportEncryptedBackup('test-password-123');const data=a.inspectBackup({password:'test-password-123',base64:b.base64});assert.equal(data.tables.documents.some(r=>r.key.startsWith('atlas-boss-account-sync-')),false);a.restoreEncryptedBackup({password:'test-password-123',base64:b.base64,confirm:true});assert.equal(a.accountSyncSettings().enabled,false);a.closeAtlas()})

test('BOSS messageType preserves text, media and cards while excluding system notices from text metrics',()=>{const {a}=fixture();a.saveBossSnapshot(snap('a',[contact()],convo([{mid:'out',isSelf:true,messageType:'text',text:'您好',time:stamp},{mid:'system',isSelf:false,status:3,messageType:'text',text:'平台通知',time:stamp+100},{mid:'card',isSelf:false,messageType:'dialog',dialogType:8,time:stamp+200},{mid:'image',isSelf:false,messageType:'image',image:{url:'sensitive-link'},time:stamp+300}])));let d=a.bossConversationDetail({accountId:'a',bossId:'b'});assert.equal(d.messages.find(m=>m.id==='out').type,'text');assert.equal(d.messages.find(m=>m.id==='system').type,'system');assert.equal(d.messages.find(m=>m.id==='card').cardType,8);assert.equal(d.messages.find(m=>m.id==='image').image,undefined);assert.equal(a.bossCommunicationMetrics().outboundConversations,1);assert.equal(a.bossCommunicationMetrics().textReplyConversations,0);a.saveBossSnapshot(snap('a',[],convo([{mid:'real',isSelf:false,messageType:'text',text:'方便了解一下',time:stamp+400}])));assert.equal(a.bossCommunicationMetrics().textReplyConversations,1);a.closeAtlas()})

test('public JD without an address is retained, while an empty interstitial is rejected',()=>{const {a}=fixture();a.saveBossSnapshot(snap());const nodes={'.job-primary h1, .job-banner h1':{innerText:'AI产品负责人'},'.job-sec-text':{innerText:'要求：企业技能平台建设'}};const document={location:{pathname:'/job_detail/j.html',hostname:'www.zhipin.com'},defaultView:{},querySelector:s=>nodes[s]||null,querySelectorAll:()=>[]};const read=()=>vm.runInNewContext('('+a.readBossPageSnapshot.toString()+')()',{document});const snapshot=read();assert.equal(snapshot.publicJobs.length,1);assert.equal(a.ingestBossPublicJobs(snapshot.publicJobs).saved,1);assert.equal(a.bossSyncCoverage().descriptions,1);assert.equal(a.bossSyncCoverage().addresses,0);delete nodes['.job-primary h1, .job-banner h1'];delete nodes['.job-sec-text'];assert.equal(read().publicJobs.length,0);a.closeAtlas()})
test('sync results expose specific missing fields and attempts without declaring full history complete',()=>{const {a,call}=fixture();a.saveBossSnapshot(snap('a',[contact()],convo([msg('1',false,'测试正文')])));a.ingestBossJobs('a',job({address:'',salaryDesc:'面议'}),detailPath);a.recordBossJobRead('a','j',{state:'observed',reason:'平台未返回地址'});let report=call('career-boss-sync-report',{onlyMissing:true});assert.equal(report.outcome,'partial');assert.equal(report.missing,1);assert.equal(report.items[0].messages,1);assert.deepEqual(Array.from(report.items[0].jobs[0].missing),['薪资区间','工作地址']);assert.equal(report.items[0].jobs[0].reason,'平台未返回地址');assert.equal(report.coverage.unknownHistory,true);a.ingestBossJobs('a',job(),detailPath);report=call('career-boss-sync-report',{});assert.equal(report.missing,0);assert.equal(report.outcome,'available');assert.match(report.outcomeLabel,/历史未验证/);a.closeAtlas()})
test('sync results isolate accounts and paginate missing-first without leaking message content',()=>{const {a,call}=fixture();a.saveBossSnapshot(snap('a',Array.from({length:43},(_,i)=>contact('b'+i,'j'+i))));let r=call('career-boss-sync-report',{page:2});assert.equal(r.total,43);assert.equal(r.items.length,20);assert.equal(r.items.some(c=>'lastText' in c),false);a.saveBossSnapshot(snap('other',[]));assert.equal(call('career-boss-sync-report',{}).total,0);assert.throws(()=>call('career-boss-sync-report',{accountId:'a'}),/账号/);assert.throws(()=>call('career-boss-sync-control',{action:'sync-now',accountId:'a'}),/账号/);a.closeAtlas()})
test('immediate sync is a read request and never changes global sending policy',()=>{const {a,call}=fixture();a.saveBossSnapshot(snap());const before=JSON.stringify(call('career-tasks-load').policy);let state=call('career-boss-sync-control',{action:'sync-now',accountId:'a'});assert.equal(state.state,'queued');assert.equal(state.enabled,true);assert.ok(state.retryRequestedAt);assert.equal(JSON.stringify(call('career-tasks-load').policy),before);a.closeAtlas()})
test('article cards, actions and links have explicit types and do not count as recruiter text replies',()=>{const {a}=fixture();a.saveBossSnapshot(snap('a',[contact()],convo([{mid:'1',isSelf:false,messageType:'articles',time:stamp},{mid:'2',isSelf:false,messageType:'action',text:'平台操作',time:stamp},{mid:'3',isSelf:false,messageType:'hyperLink',time:stamp}])));assert.deepEqual(Array.from(a.bossConversationDetail({accountId:'a',bossId:'b'}).messages.map(m=>m.type)).sort(),['action','card','link']);assert.equal(a.bossCommunicationMetrics().outboundConversations,0);a.closeAtlas()})
