const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),vm=require('node:vm'),{buildSync}=require('esbuild')
const root=fs.mkdtempSync(path.join(os.tmpdir(),'atlas-model-test-')),bundle=path.join(root,'api.cjs')
buildSync({stdin:{resolveDir:process.cwd(),contents:['atlas-model-config','atlas-model-transport','atlas-deepseek','atlas-store','atlas-policy','atlas-ai','atlas-greeting','atlas-task-queue'].map(n=>`export * from './packages/ui/src/main/features/${n}'`).join('\n')},bundle:true,platform:'node',format:'cjs',outfile:bundle})
process.on('exit',()=>fs.rmSync(root,{recursive:true,force:true}))
const catalog={data:[{id:'deepseek/deepseek-v4.1-flash',name:'DeepSeek V4.1 Flash',context_length:1000000,supported_endpoints:['/chat/completions','/responses']},{id:'claude-sonnet-4-6',name:'Claude',context_length:1000000,supported_endpoints:['/messages']},{id:'future',supported_endpoints:['/responses']}]}
const plain=x=>JSON.parse(JSON.stringify(x))
function fixture(){const home=fs.mkdtempSync(path.join(root,'home-'));fs.mkdirSync(path.join(home,'.local/share/zhitu-atlas/config'),{recursive:true});const m={exports:{}},state={requests:[],handler:null};vm.runInNewContext('(function(require,module,exports){'+fs.readFileSync(bundle,'utf8')+'\n})',{Buffer,process,Date,URL,AbortController,AbortSignal,setTimeout,clearTimeout,setInterval,clearInterval,fetch:async(url,o)=>{const b=o.body?JSON.parse(o.body):null;state.requests.push({url,body:b,headers:o.headers});if(!b)return{ok:true,json:async()=>catalog};if(state.handler)return state.handler(b,o);return{ok:true,json:async()=>({choices:[{message:{content:'{"ok":true}'},finish_reason:'stop'}],usage:{total_tokens:10}})}}})(k=>k==='node:os'?{homedir:()=>home}:require(k),m,m.exports);const a=m.exports;return{a,state,home,async save(model='deepseek/deepseek-v4.1-flash',secret='user_isolated_test_key'){return a.saveModelSettings({model,provider:'commandcode',secret,baseRevision:a.modelSettings().revision})},close:()=>a.closeAtlas()}}
function toolReply(name='atlas_connection_probe',id='call-1',args='{"value":7}'){return{ok:true,json:async()=>({choices:[{message:{role:'assistant',content:null,reasoning_content:'reasoning preserved',tool_calls:[{id,type:'function',function:{name,arguments:args}}]},finish_reason:'tool_calls'}],usage:{prompt_tokens:3,completion_tokens:2,total_tokens:5}})}}
test('catalog retains every model, endpoint routing and unknown capacity without fabricated capabilities',()=>{const f=fixture();const m=f.a.parseModelCatalog(catalog);assert.equal(m.length,3);assert.equal(m[1].protocol,'anthropic');assert.equal(m[2].protocol,null);assert.equal(m[2].contextLength,null);assert.throws(()=>f.a.parseModelCatalog({data:[...catalog.data,catalog.data[0]]}),/重复/);f.close()})
test('save chooses correct route; switch keeps credentials, exposes no secret, rejects stale revision',async()=>{const f=fixture();let s=await f.save();assert.equal(s.model,catalog.data[0].id);assert.equal(s.generation.reasoning_effort,undefined);assert.equal(s.generation.max_tokens,4096);assert.equal(s.contextWindowTokens,1000000);const initial=s.revision;s=await f.a.saveModelSettings({provider:'commandcode',model:'claude-sonnet-4-6',secret:'',baseRevision:s.revision});assert.equal(s.protocol,'anthropic');assert.equal(s.url.endsWith('/messages'),true);assert.equal(s.generation.max_tokens,4096);assert.equal(s.generation.thinking,undefined);assert.equal(f.a.modelConfig().key,'user_isolated_test_key');assert.ok(!JSON.stringify(s).includes('user_isolated'));await assert.rejects(f.a.saveModelSettings({model:'future',baseRevision:initial}),/已变化/);await assert.rejects(f.a.saveModelSettings({model:'future',baseRevision:s.revision}),/支持 Chat/);assert.equal(fs.statSync(path.join(f.home,'.local/share/zhitu-atlas/private/models.json')).mode&0o777,0o600);f.close()})
test('host allowlist prevents credential forwarding to lookalike and redirected endpoints',()=>{const f=fixture();for(const url of ['https://api.commandcode.ai.evil/provider/v1','https://api.commandcode.ai/provider/v1?next=evil','http://api.commandcode.ai/provider/v1','https://user:pass@api.deepseek.com','https://api.commandcode.ai/provider/v1/evil'])assert.equal(f.a.providerOf({providerCompleteApiUrl:url}),null);f.close()})
test('Chat tool roundtrip preserves reasoning, returns JSON and sums both requests',async()=>{const f=fixture();const c=await f.save();f.state.handler=b=>b.messages.some(m=>m.role==='tool')?{ok:true,json:async()=>({choices:[{message:{content:'{"ok":true,"answer":"atlas-tool-ok"}'},finish_reason:'stop'}],usage:{total_tokens:11}})}:toolReply();const r=await f.a.testModel({baseRevision:c.revision});assert.equal(r.toolCalling,true);assert.equal(r.usage.total_tokens,16);assert.equal(r.usage.requestCount,2);assert.equal(r.usage.toolCalls,1);const second=f.state.requests.filter(r=>r.body)[1];assert.equal(second.body.messages.at(-2).reasoning_content,'reasoning preserved');assert.equal(f.a.modelSettings().verification.toolCalling,true);f.close()})
test('Anthropic tools use native blocks, no DeepSeek parameters, and normalize usage',async()=>{const f=fixture();await f.save('claude-sonnet-4-6');f.state.handler=(b,o)=>{assert.equal(b.response_format,undefined);assert.equal(b.reasoning_effort,undefined);assert.equal(o.headers['anthropic-version'],'2023-06-01');return b.messages.length===1?{ok:true,json:async()=>({content:[{type:'tool_use',id:'t1',name:'atlas_connection_probe',input:{value:7}}],stop_reason:'tool_use',usage:{input_tokens:2,output_tokens:3}})}:{ok:true,json:async()=>({content:[{type:'text',text:'{"ok":true,"answer":"atlas-tool-ok"}'}],stop_reason:'end_turn',usage:{input_tokens:4,output_tokens:5}})}};const r=await f.a.testModel({baseRevision:f.a.modelSettings().revision});assert.equal(r.toolCalling,true);assert.equal(r.usage.total_tokens,14);const bodies=f.state.requests.filter(r=>r.body);assert.equal(bodies[1].body.messages.at(-1).content[0].type,'tool_result');f.close()})
test('unknown tool or malformed arguments cannot invoke any action',async()=>{for(const reply of [toolReply('send_message'),toolReply('atlas_connection_probe','c','{"path":"/etc/passwd"}'),toolReply('atlas_connection_probe','c','not json')]){const f=fixture();await f.save();f.state.handler=()=>reply;await assert.rejects(f.a.testModel({baseRevision:f.a.modelSettings().revision}),/工具|JSON/);assert.equal(f.state.requests.filter(r=>r.body).length,1);f.close()}})
test('tools only read confirmed snapshot evidence and reject extra arguments',()=>{const f=fixture();const t=f.a.evidenceTools({evidence:[{id:'e1',confirmed:true,text:'事实',source:'本人'},{id:'e2',confirmed:false,text:'待核实'}]})[0];const r=plain(t.run({ids:['e1','e2','fake']}));assert.equal(r.evidence[0].text,'事实');assert.ok(r.evidence[1].error);assert.ok(r.evidence[2].error);assert.throws(()=>t.run({ids:['e1'],execute:'send'}),/无效/);f.close()})
test('bounded loop rejects repeated call ids and never silently retries',async()=>{const f=fixture();await f.save();f.state.handler=()=>toolReply();await assert.rejects(f.a.testModel({baseRevision:f.a.modelSettings().revision}),/重复/);assert.equal(f.state.requests.filter(r=>r.body).length,2);f.close()})
test('network / auth / output errors keep failed attempt count and do not log provider secrets',async()=>{for(const mode of ['network','auth','invalid']){const f=fixture();await f.save();f.state.handler=()=>{if(mode==='network')throw Error('user_provider_secret');if(mode==='auth')return{ok:false,status:401};return{ok:true,json:async()=>({choices:[{message:{content:'invalid'},finish_reason:'stop'}],usage:{total_tokens:12}})}};let message='';try{await f.a.testModel({baseRevision:f.a.modelSettings().revision})}catch(e){message=e.message}assert.ok(!message.includes('user_provider_secret'));assert.equal(f.state.requests.filter(r=>r.body).length,1);assert.equal(f.a.modelUsage().calls[0].usage.requestCount,1);assert.equal(f.a.modelUsage().calls[0].status,'failed');f.close()}})
test('generation alone cannot claim tool verification',async()=>{const f=fixture();await f.save();const r=await f.a.testModel({baseRevision:f.a.modelSettings().revision});assert.equal(r.generation,true);assert.equal(r.toolCalling,false);f.close()})
test('model change invalidates prompts/caches and stops an in-flight tool continuation',async()=>{const f=fixture();await f.save();const original=f.a.currentAnalysisPromptVersion(),greeting=f.a.currentGreetingPromptVersion();f.state.handler=async()=>{await f.save('claude-sonnet-4-6');return toolReply()};await assert.rejects(f.a.testModel({baseRevision:f.a.modelSettings().revision}),/配置已更新/);assert.notEqual(f.a.currentAnalysisPromptVersion(),original);assert.notEqual(f.a.currentGreetingPromptVersion(),greeting);assert.equal(f.state.requests.filter(r=>r.body).length,1);assert.equal(f.a.modelSettings().verification,null);f.close()})
test('cancelled request never sends a tool continuation',async()=>{const f=fixture();await f.save();const c=new AbortController();f.state.handler=()=>{c.abort();return toolReply()};await assert.rejects(f.a.testModel({baseRevision:f.a.modelSettings().revision,signal:c.signal}),/取消/);assert.equal(f.state.requests.filter(r=>r.body).length,1);f.close()})
test('tool continuation consumes automatic generation budget, including failures',async()=>{const f=fixture();await f.save();f.a.initializePolicy();let p=f.a.careerPolicy();p.discovery.aiLimit=1;p.automationPaused=false;f.a.atlasWrite('atlas-career-policy',p);f.state.handler=()=>toolReply('atlas_read_confirmed_evidence','c','{"ids":["e1"]}');await assert.rejects(f.a.deepseekJson(f.a.modelConfig(),'ignored',{evidence:[{id:'e1',text:'事实',confirmed:true}]},new AbortController().signal,{kind:'analysis',automatic:true}),/预算/);assert.equal(f.state.requests.filter(r=>r.body).length,1);assert.equal(f.a.modelUsage().automaticAnalysis,1);f.close()})
test('persistent diagnostic tasks reject secrets and custom prompts',()=>{const f=fixture();assert.throws(()=>f.a.createTask({channel:'career-model-test',payload:{secret:'user_hidden'}}),/不接受密钥/);const x=f.a.createTask({channel:'career-model-test',payload:{baseRevision:'r'}}),y=f.a.createTask({channel:'career-model-test',payload:{baseRevision:'r'}});assert.equal(x.taskId,y.taskId);f.close()})
function sse(events){const text=events.map(e=>'data: '+(typeof e==='string'?e:JSON.stringify(e))+'\r\n\r\n').join(''),bytes=Buffer.from(text);return new Response(new ReadableStream({start(controller){for(let i=0;i<bytes.length;i+=7)controller.enqueue(bytes.subarray(i,i+7));controller.close()}}),{headers:{'content-type':'text/event-stream'}})}
test('Chat streaming reconstructs fragmented tools and Chinese UTF-8 with usage',async()=>{const f=fixture();const r=await f.a.readModelStream(sse([{choices:[{delta:{reasoning_content:'先核实',tool_calls:[{index:0,id:'t1',function:{name:'atlas_connection_probe',arguments:'{'}}]}}]},{choices:[{delta:{tool_calls:[{index:0,function:{arguments:'}'}}]},finish_reason:'tool_calls'}]},{choices:[],usage:{total_tokens:15}},'[DONE]']),false,new AbortController().signal);assert.equal(r.choices[0].message.reasoning_content,'先核实');assert.equal(r.choices[0].message.tool_calls[0].function.arguments,'{}');assert.equal(r.usage.total_tokens,15);f.close()})
test('Anthropic streaming reconstructs tool inputs and retains thinking signatures',async()=>{const f=fixture();const r=await f.a.readModelStream(sse([{type:'message_start',message:{usage:{input_tokens:4}}},{type:'content_block_start',index:0,content_block:{type:'thinking',thinking:''}},{type:'content_block_delta',index:0,delta:{type:'thinking_delta',thinking:'核实'}},{type:'content_block_delta',index:0,delta:{type:'signature_delta',signature:'sig'}},{type:'content_block_start',index:1,content_block:{type:'tool_use',id:'c',name:'atlas_connection_probe',input:{value:7}}},{type:'content_block_delta',index:1,delta:{type:'input_json_delta',partial_json:'{}'}},{type:'message_delta',delta:{stop_reason:'tool_use'},usage:{output_tokens:5}},{type:'message_stop'}]),true,new AbortController().signal);assert.equal(r.content[0].signature,'sig');assert.deepEqual(plain(r.content[1].input),{});assert.equal(r.usage.input_tokens,4);assert.equal(r.usage.output_tokens,5);f.close()})
test('truncated stream, provider stream errors and excess tool indices fail closed',async()=>{const f=fixture();for(const data of [[{choices:[{delta:{content:'{"ok":true}'}}]}],[{error:{message:'upstream secret never surfaced'}}],[{choices:[{delta:{tool_calls:[{index:1000}]}}]}]])await assert.rejects(f.a.readModelStream(sse(data),false,new AbortController().signal),/模型/);f.close()})
test('streaming transport accepts a complete JSON result but refuses unfinished output',async()=>{const f=fixture();await f.save();f.state.handler=()=>sse([{choices:[{delta:{content:'{"ok":true}'},finish_reason:'stop'}]},{usage:{total_tokens:19}}]);const r=await f.a.modelJsonTransport(f.a.modelConfig(),'JSON',{},new AbortController().signal);assert.equal(r.value.ok,true);assert.equal(r.usage.total_tokens,19);assert.equal(f.state.requests.at(-1).body.stream,true);f.close()})

test('aborting a silent model stream releases the reader immediately',async()=>{const f=fixture(),controller=new AbortController();let cancelled=false;const stream=new ReadableStream({cancel(){cancelled=true}});const result=f.a.readModelStream(new Response(stream),false,controller.signal);controller.abort();await assert.rejects(result,/取消/);assert.equal(cancelled,true);f.close()})

test('existing DeepSeek settings retain max and 384K; new settings support task budgets',async()=>{
 const f=fixture();fs.writeFileSync(path.join(f.home,'.local/share/zhitu-atlas/config/llm.json'),JSON.stringify([{enabled:true,model:'deepseek-flash',providerCompleteApiUrl:'https://api.deepseek.com/chat/completions',providerApiSecret:'fixture-legacy-key'}]));
 const c=f.a.modelConfig();assert.equal(c.generation.reasoning_effort,'max');assert.equal(c.generation.max_tokens,393216);assert.equal(f.a.modelForTask(c,'reply').generation.max_tokens,393216);
 await f.a.saveModelSettings({provider:'deepseek',model:'deepseek-flash',baseRevision:f.a.modelSettings().revision});assert.equal(f.a.modelConfig().generation.reasoning_effort,'max');
 const options={maxOutputTokens:8192,budgetMode:'task',reasoning:'default',toolsEnabled:true,jsonMode:true};await f.a.saveModelSettings({provider:'deepseek',model:'deepseek-flash',generationOptions:options,baseRevision:f.a.modelSettings().revision});
 assert.equal(f.a.modelForTask(f.a.modelConfig(),'reply').generation.max_tokens,2048);assert.equal(f.a.modelForTask(f.a.modelConfig(),'analysis').generation.max_tokens,8192);f.close();
})
test('compatible endpoints bind secrets to address and never inherit another provider credential',async()=>{
 const f=fixture();await f.save();const save=extra=>f.a.saveModelSettings({provider:'compatible',baseUrl:'https://llm.example.invalid/v1',model:'example-model',baseRevision:f.a.modelSettings().revision,...extra});
 await assert.rejects(save({}),/密钥/);const c=await save({secret:'fixture-custom-key'});assert.equal(c.url,'https://llm.example.invalid/v1/chat/completions');assert.equal(c.generation.reasoning_effort,undefined);assert.ok(!JSON.stringify(c).includes('fixture-custom-key'));
 await assert.rejects(save({baseUrl:'https://other.example.invalid/v1'}),/更换地址/);await save({model:'example-other'});assert.equal(f.a.modelConfig().key,'fixture-custom-key');
 for(const baseUrl of ['http://remote.example.invalid/v1','https://user:pass@example.invalid/v1','https://example.invalid/v1?key=test','file:///etc/passwd','http://169.254.169.254/v1'])await assert.rejects(save({baseUrl,secret:'fixture-key'}));f.close();
})
test('loopback compatible model supports no key and structured tool roundtrips',async()=>{
 const f=fixture();const c=await f.a.saveModelSettings({provider:'compatible',baseUrl:'http://127.0.0.1:11434/v1',model:'local-model',generationOptions:{maxOutputTokens:4096,budgetMode:'task',reasoning:'default',toolsEnabled:true,jsonMode:false},baseRevision:f.a.modelSettings().revision});
 f.state.handler=(b,o)=>{assert.equal(o.headers.Authorization,undefined);assert.equal(b.reasoning_effort,undefined);assert.equal(b.response_format,undefined);assert.equal(b.max_tokens,1024);return b.messages.some(m=>m.role==='tool')?{ok:true,json:async()=>({choices:[{message:{content:'{"ok":true,"answer":"atlas-tool-ok"}'},finish_reason:'stop'}]})}:toolReply()};
 const r=await f.a.testModel({baseRevision:c.revision});assert.equal(r.toolCalling,true);assert.equal(r.usage.requestCount,2);f.close();
})
test('new install stays paused without changing a saved existing policy',()=>{
 const f=fixture();const p=f.a.initializePolicy().value;assert.deepEqual(Array.from(p.conflicts),[]);assert.equal(p.automationPaused,true);assert.equal(p.discovery.autoRecommend,false);assert.equal(p.sending.paused,true);assert.equal(p.sending.outbound,false);
 const existing={...p,automationPaused:false,sending:{...p.sending,paused:false,outbound:true}};f.a.atlasWrite('atlas-career-policy',existing);assert.equal(f.a.initializePolicy().value.sending.paused,false);assert.equal(f.a.careerPolicy().automationPaused,false);f.close();
})
