const {test}=require('node:test'),assert=require('node:assert/strict'),{buildSync}=require('esbuild'),vm=require('node:vm');
const code=buildSync({stdin:{contents:"export * from './packages/ui/src/common/opportunity-map';export * from './packages/ui/src/common/regions'",resolveDir:process.cwd()},bundle:true,platform:'node',format:'cjs',write:false}).outputFiles[0].text,m={exports:{}};vm.runInNewContext('(function(module,exports){'+code+'})',{})(m,m.exports);const a=m.exports;
const opp=(id,city,address,extra={})=>({id,stage:'已沟通',job:{companyName:'企业'+id,jobName:'产品经理',cityName:city,address},...extra});
test('default map uses saved target city and never hardcodes Shanghai for new installations',()=>{assert.equal(a.defaultMapCity(['杭州市','上海']),'杭州');assert.equal(a.defaultMapCity([]),'');assert.equal(a.defaultMapCity(['未知地区','北京']),'北京')});
test('all supported regions have valid sourced map centres, with explicit fallback precision',()=>{assert.equal(Object.keys(a.mapPlaces).length,a.recruitmentCities.length);for(const city of a.recruitmentCities){const p=a.mapPlaces[city.name];assert.ok(a.validCoordinates(p.lng,p.lat));assert.match(p.sourceId,/^\d+$/);assert.ok(['city','province'].includes(p.level))}assert.equal(a.mapPlaces['上海'].level,'city');assert.equal(a.mapPlaces['新星市'].level,'province')});
test('nationwide map aggregates by city while city map aggregates by district',()=>{const items=[opp('1','上海','上海市徐汇区'),opp('2','上海','上海市浦东新区'),opp('3','北京','北京市海淀区')];const national=a.regionalMapGroups(items);assert.equal(national.length,2);assert.equal(national.find(g=>g.city==='上海').items.length,2);const sh=a.regionalMapGroups(items,'上海');assert.equal(sh.length,2);assert.deepEqual(sh.map(g=>g.district).sort().join(','),'徐汇区,浦东新区');assert.equal(a.regionalMapGroups(items,'成都').length,0)});
test('precise, regional and unknown coordinates do not mix or mutate opportunities',()=>{const precise=opp('p','上海','上海市徐汇区',{lng:121.43,lat:31.19,crs:'wgs84'}),gcj=opp('g','上海','上海市徐汇区',{lng:121.43,lat:31.19,crs:'gcj02'}),unknown=opp('u','',''),conflict=opp('c','上海','海淀区中关村');const items=[precise,gcj,unknown,conflict],before=JSON.stringify(items),groups=a.regionalMapGroups(items,'上海');assert.equal(groups.length,1);assert.equal(groups[0].items[0].id,'g');assert.equal(JSON.stringify(items),before);assert.equal(a.preciseMapLocation(precise),true);assert.equal(a.preciseMapLocation(gcj),false)});
test('district anchors are matched within city, not same-name districts elsewhere',()=>{const items=[opp('1','北京','北京市朝阳区'),opp('2','长春','长春市朝阳区')];const beijing=a.regionalMapGroups(items,'北京')[0],changchun=a.regionalMapGroups(items,'长春')[0];assert.ok(beijing.lat<41);assert.ok(changchun.lat>43);assert.notEqual(beijing.lng,changchun.lng)});

test('national city aggregates include exact pins once, avoiding overlapping city markers',()=>{const items=[opp('1','上海','上海市徐汇区'),opp('2','上海','上海市徐汇区',{lat:31.19,lng:121.43,crs:'wgs84'})];const national=a.regionalMapGroups(items);assert.equal(national.length,1);assert.equal(national[0].items.length,2);assert.equal(a.regionalMapGroups(items,'上海')[0].items.length,1)});
