<template><main class="atlas-settings"><header><div><h1>设置</h1><p>统一模型、连接和数据管理，保留全部历史与迁移依据。</p></div><ElButton @click="load">更新状态</ElButton></header><ElAlert v-if="error" :title="error" type="error" :closable="false" /><ElTabs v-model="tab"><ElTabPane label="开始使用" name="start"><SetupGuide /></ElTabPane><ElTabPane label="模型与 AI 用量" name="model"><ModelSettings /></ElTabPane><ElTabPane label="地图" name="map"><MapSettings /></ElTabPane><ElTabPane label="数据管理" name="data"><AtlasOperations section="data" /></ElTabPane><ElTabPane label="连接与策略" name="connection"><div class="cards"><section class="panel"><h2>BOSS 账号与连接</h2><p>当前账号：{{ data?.connection.account || '尚未核实' }}</p><p>已读取 {{ data?.connection.syncedCount || 0 }} 个会话，完整历史需单独核对。</p><ElButton type="primary" @click="router.push('/main-layout/CareerBoss')">打开 BOSS 工作台</ElButton><ElButton @click="router.push('/main-layout/CareerTasks?tab=sync')">同步覆盖与诊断</ElButton></section><section class="panel"><h2>统一求职策略</h2><p>城市、月薪、核心关键词与排除条件在机会发现统一修改。</p><ElButton @click="router.push('/main-layout/CareerDiscovery?settings=1')">编辑求职策略</ElButton><p>自动发送的限额和运行时段在任务中心管理，常规回复与重要事项确认在沟通中心管理。</p></section></div><details class="panel"><summary>桌面运行与连接</summary><p>内嵌工作台与独立窗口共用同一 BOSS 登录会话，无需安装或配置外部浏览器。</p><p v-if="runtimeInfo">版本 {{ runtimeInfo.version }} · {{ runtimeInfo.browser }}<br />资料目录：{{ runtimeInfo.dataRoot }}</p><ElButton v-if="runtime==='desktop'" @click="browser">读取运行信息</ElButton><p v-else>原生 BOSS 会话由桌面程序管理。</p></details></ElTabPane><ElTabPane label="迁移档案" name="archive"><section class="panel"><h2>旧版数据只读档案</h2><p>原始记录保留来源和账号归属。未知账号的数据不并入当前账号；名称相似不会自动合并企业。</p><label>归属范围 <select v-model="archiveAccount" @change="page=1;loadArchive()"><option value="">当前账号档案</option><option value="unassigned">待归属档案</option></select></label><ElButton @click="loadArchive">读取档案</ElButton><p v-if="archive">共 {{ archive.total }} 条 · 第 {{ page }} 页</p><article v-for="r in archive?.items" :key="r.source_table+r.source_id+r.account_id" class="archive-row"><details><summary>{{ r.source_table }} · {{ r.source_id }} · {{ r.account_id || '账号待归属' }}</summary><pre>{{ JSON.stringify(r.body,null,2) }}</pre></details></article><nav><ElButton :disabled="page<=1" @click="page--;loadArchive()">上一页</ElButton><ElButton :disabled="!archive || page*20>=archive.total" @click="page++;loadArchive()">下一页</ElButton></nav></section></ElTabPane></ElTabs></main></template>
<script setup lang="ts">
import MapSettings from '../../components/career/MapSettings.vue'
import SetupGuide from '../../components/career/SetupGuide.vue'
import {ref,inject,onMounted,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {ElAlert,ElButton,ElTabs,ElTabPane} from 'element-plus'
import ModelSettings from '../../components/career/ModelSettings.vue'
import AtlasOperations from '../../components/career/AtlasOperations.vue'
const route=useRoute(),router=useRouter(),runtime=inject('atlas-runtime','desktop'),tab=ref(String(route.query.section||'model')),data=ref<any>(),error=ref(''),archive=ref<any>(),archiveAccount=ref(''),page=ref(1),runtimeInfo=ref<any>()
async function load(){try{data.value=await electron.ipcRenderer.invoke('career-dashboard-load');error.value=''}catch(e){error.value=String(e)}}
async function browser(){try{runtimeInfo.value=await electron.ipcRenderer.invoke('atlas-runtime-info')}catch(e){error.value=String(e)}}
async function loadArchive(){try{archive.value=await electron.ipcRenderer.invoke('career-legacy-archive',{page:page.value,unassigned:archiveAccount.value==='unassigned'});error.value=''}catch(e){error.value=String(e)}}
watch(()=>route.query.section,v=>{if(v)tab.value=String(v)});
watch(tab,v=>{if(v==='archive')void loadArchive()});onMounted(()=>{if(route.query.section==='tasks')void router.replace('/main-layout/CareerTasks');else{void load();if(tab.value==='archive')void loadArchive()}})
</script>
<style scoped>
.atlas-settings{height:100%;overflow:auto;box-sizing:border-box;padding:30px;font-size:13px}.atlas-settings>header{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:20px}h1{font-size:28px;margin:12px 0}small{color:var(--el-color-primary);letter-spacing:1.8px}p{line-height:1.8;color:var(--el-text-color-secondary)}.panel{padding:24px;border:1px solid var(--el-border-color);border-radius:12px;background:var(--atlas-panel);margin-bottom:20px}.cards{display:grid;grid-template-columns:1fr 1fr;gap:20px}.cards h2{font-size:18px}.cards .el-button{margin:6px 10px 6px 0}summary{cursor:pointer;color:var(--el-color-primary)}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}.archive-row{padding:16px 0;border-bottom:1px solid var(--el-border-color)}nav{display:flex;justify-content:flex-end;margin-top:20px}select{padding:8px;margin:10px;border:1px solid var(--el-border-color);border-radius:6px;color:inherit;background:var(--atlas-panel)}@media(max-width:900px){.cards{grid-template-columns:1fr}.atlas-settings{padding:20px}}
</style>
