import { createApp } from 'vue'
import { createPinia } from 'pinia'
import ElementPlus from 'element-plus'
import App from './App.vue'
import router from './router'
import 'element-plus/dist/index.css'
import './style/base.scss'
import './style/atlas-theme.scss'
import 'virtual:uno.css'
document.documentElement.dataset.theme = 'daylight'
createApp(App).use(createPinia()).use(router).use(ElementPlus).mount('#app')
